# Maintainer: xXCoolinXx collin.t.francel@gmail.com
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=xo-rs-bin
pkgver=0.4.0
pkgrel=1
pkgdesc="TicTacToe terminal game with Rust"
url="https://github.com/xXCoolinXx/xo-rs"
license=("GPL-3.0-or-later")
arch=("x86_64")
provides=("xo-rs")
conflicts=("xo-rs")
source=("https://github.com/xXCoolinXx/xo-rs/releases/download/v$pkgver/xo-rs-$pkgver-x86_64.tar.gz")
sha256sums=("ac4bc910a6fda7ed3daebfd4c3767312a0cd585da0d3c6e9e6856450af11f735")

package() {
    install -Dm755 xo-rs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
